import type { Metadata } from "next";
import "app/styles/index.scss";
import { Header } from "widgets/Header";
import { Footer } from "widgets/Footer";
import { StoreProvider } from "app/Providers/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
