import { Task } from "entities/Task";

export enum TaskValidationError {
    NO_DATA = 'NO_DATA',
    INCORRECT_TITLE = 'INCORRECT_TITLE',
    INCORRECT_DESCRIPTION = 'INCORRECT_DESCRIPTION',
    INCORRECT_DEADLINE = 'INCORRECT_DEADLINE',
    INCORRECT_PRIORITY = 'INCORRECT_PRIORITY',
    INCORRECT_STATUS = 'INCORRECT_STATUS',
    INCORRECT_ASSIGNEE = 'INCORRECT_ASSIGNEE',
    INCORRECT_CATEGORY = 'INCORRECT_CATEGORY',
    EMPTY_TAGS = 'EMPTY_TAGS',
    EMPTY_ATTACHMENTS = 'EMPTY_ATTACHMENTS',
    INCORRECT_ESTIMATED_TIME = 'INCORRECT_ESTIMATED_TIME',
    INCORRECT_BUDGET = 'INCORRECT_BUDGET',
    SERVER_ERROR = 'SERVER_ERROR'
} 

export interface CreateTaskFormSchema {
    formData?: Task
    isLoading: boolean
    error?: TaskValidationError[]
}