import { Vacancy } from "entities/Vacancy";

export enum ValidateVacancyError {
    NO_DATA = 'NO_DATA',
    INCORRECT_TITLE = 'INCORRECT_TITLE',
    INCORRECT_DESCRIPTION = 'INCORRECT_DESCRIPTION',
    INCORRECT_COMPANY = 'INCORRECT_COMPANY',
    INCORRECT_LOCATION = 'INCORRECT_LOCATION',
    INCORRECT_EMAIL = 'INCORRECT_EMAIL',
    INCORRECT_EMPLOYMENT_TYPE = 'INCORRECT_EMPLOYMENT_TYPE',
    INCORRECT_EXPERIENCE_LEVEL = 'INCORRECT_EXPERIENCE_LEVEL',
    INCORRECT_SALARY = 'INCORRECT_SALARY',
    EMPTY_RESPONSIBILITIES = 'EMPTY_RESPONSIBILITIES',
    EMPTY_REQUIREMENTS = 'EMPTY_REQUIREMENTS',
    EMPTY_CONDITIONS = 'EMPTY_CONDITIONS',
    EMPTY_SKILLS = 'EMPTY_SKILLS',
    SERVER_ERROR='SERVER_ERROR'
}

export interface CreateVacancyFormSchema {
    formData?: Vacancy
    isLoading: boolean
    error?: ValidateVacancyError[]
}